version: '3'
services:
    web:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - .:/myapp
    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"